SAMHS/SAMHS.UI/Models/Deposito.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SAMHS.UI.Models
{
    public class Deposito
    {
        public string confirmacion { get; set; }
        public Exception error { get; set; }
        public void SubirArchivo ( String ruta, HttpPostedFileBase file)
        {
            try
            {
                file.SaveAs(ruta);
                this.confirmacion = "Recibo del depósito enviado";
            }
            catch (Exception ex)
            {

                this.error = ex;
            }
        }
    }
}

SAMHS/SAMHS.UI/Controllers/CalendarioController.cs
using AutoMapper;
using SAMHS.DAL.Interfaces;
using SAMHS.DAL.Metodos;
using SAMHS.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SAMHS.UI.Controllers
{
    public class CalendarioController : Controller
    {

        ICalendario cal;

        public CalendarioController()
        {
            cal = new MCalendario();

        }
        // GET: Calendario
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetEvents()
        {
            Calendario modelo = new Calendario();
            {
                var events = modelo.ToString();
                return new JsonResult { Data = events, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
            }
        }

        //public ActionResult GetEvents()
        //{
        //    var listaCalendario = cal.ListaCalendario();
        //    var calendariosListar = Mapper.Map<List<Models.Calendario>>(listaCalendario);
        //    return View(calendariosListar);
        //}
    }
}

SAMHS/SAMHS.UI/Controllers/CitasController.cs
using AutoMapper;
using SAMHS.DAL.Interfaces;
using SAMHS.DAL.Metodos;
using SAMHS.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SAMHS.UI.Controllers
{
    public class CitasController : Controller
    {
       
        ICitas cit;
       
        public CitasController ()
        {
            cit = new MCitas();
           
        }
        // GET: Citas
        public ActionResult Index()
        {
            var listaCitas = cit.ListaCitas();
            var citasListar = Mapper.Map<List<Models.Citas>>(listaCitas);
            return View(citasListar);
        }

       

          // GET: Producto/Details/5
        public ActionResult Details(int id)
        {
            var citas = cit.BuscarCitas(id);
            var citasMostrar = Mapper.Map<Models.Citas>(citas);
            return View(citasMostrar);
        }

        // GET: Producto/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Producto/Create
        [HttpPost]
        public ActionResult Create(Citas citas)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View();
                }
                var citasInsertar = Mapper.Map<DATA.Citas>(citas);
                cit.AgregarCitas(citasInsertar);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Producto/Edit/5
        public ActionResult Edit(int id)
        {
            var citas = cit.BuscarCitas(id);
            var citasMostrar = Mapper.Map<Models.Citas>(citas);
            return View(citasMostrar);
        }

        // POST: Producto/Edit/5
        [HttpPost]
        public ActionResult Edit(Citas citas)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View();
                }
                var citasActualizar = Mapper.Map<DATA.Citas>(citas);
                cit.ActualizarCitas(citasActualizar);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Producto/Delete/5
        public ActionResult Delete(int id)
        {
            cit.EliminarCitas(id);
            return View();
        }
    }
}

SAMHS/SAMHS.UI/Controllers/HomeController.cs
using AutoMapper;
using SAMHS.DAL.Interfaces;
using SAMHS.DAL.Metodos;
using SAMHS.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SAMHS.UI.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Deposito()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Deposito (HttpPostedFileBase file)
        {
            Deposito modelo = new Deposito();
            if (file != null)
            {
                string ruta = Server.MapPath("~/Depositos/");
                ruta += file.FileName;
                modelo.SubirArchivo(ruta, file);
                ViewBag.Error = modelo.error;
                ViewBag.Correcto = modelo.confirmacion;
            }
            return View();
        }
        public ActionResult Home()
        {
            return View();
        }
    }
}

SAMHS/SAMHS.UI/Controllers/MaterialesController.cs
using AutoMapper;
using SAMHS.DAL.Interfaces;
using SAMHS.DAL.Metodos;
using SAMHS.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SAMHS.UI.Controllers
{
    public class MaterialesController : Controller
    {
        IMateriales mat;

        public MaterialesController()
        {
            mat = new MMateriales();

        }
        // GET: Materiales
        public ActionResult Index()
        {
            var listaMateriales = mat.ListaMateriales();
            var materialesListar = Mapper.Map<List<Models.Materiales>>(listaMateriales);
            return View(materialesListar);
        }



        // GET: Producto/Details/5
        public ActionResult Details(int id)
        {
            var materiales = mat.BuscarMateriales(id);
            var materialesMostrar = Mapper.Map<Models.Materiales>(materiales);
            return View(materialesMostrar);
        }

        // GET: Producto/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Producto/Create
        [HttpPost]
        public ActionResult Create(Materiales materiales)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View();
                }
                var materialesInsertar = Mapper.Map<DATA.Materiales>(materiales);
                mat.AgregarMateriales(materialesInsertar);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Producto/Edit/5
        public ActionResult Edit(int id)
        {
            var materiales = mat.BuscarMateriales(id);
            var materialesMostrar = Mapper.Map<Models.Materiales>(materiales);
            return View(materialesMostrar);
        }

        // POST: Producto/Edit/5
        [HttpPost]
        public ActionResult Edit(Materiales materiales)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View();
                }
                var materialesActualizar = Mapper.Map<DATA.Materiales>(materiales);
                mat.ActualizarMateriales(materialesActualizar);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Producto/Delete/5
        public ActionResult Delete(int id)
        {
            mat.EliminarMateriales(id);
            return View();
        }
    }
}

SAMHS/SAMHS.UI/Controllers/UniformesController.cs
using AutoMapper;
using SAMHS.DAL.Interfaces;
using SAMHS.DAL.Metodos;
using SAMHS.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SAMHS.UI.Controllers
{
    public class UniformesController : Controller
    {
        IUniformes uni;

        public UniformesController()
        {
            uni = new MUniformes();

        }
        // GET: Uniformes
        public ActionResult Index()
        {
            var listaUniformes = uni.ListaUniformes();
            var uniformesListar = Mapper.Map<List<Models.Uniformes>>(listaUniformes);
            return View(uniformesListar);
        }



        // GET: Producto/Details/5
        public ActionResult Details(int id)
        {
            var uniformes = uni.BuscarUniformes(id);
            var uniformesMostrar = Mapper.Map<Models.Uniformes>(uniformes);
            return View(uniformesMostrar);
        }

        // GET: Producto/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Producto/Create
        [HttpPost]
        public ActionResult Create(Uniformes uniformes)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View();
                }
                var uniformesInsertar = Mapper.Map<DATA.Uniformes>(uniformes);
                uni.AgregarUniformes(uniformesInsertar);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Producto/Edit/5
        public ActionResult Edit(int id)
        {
            var uniformes = uni.BuscarUniformes(id);
            var uniformesMostrar = Mapper.Map<Models.Uniformes>(uniformes);
            return View(uniformesMostrar);
        }

        // POST: Producto/Edit/5
        [HttpPost]
        public ActionResult Edit(Uniformes uniformes)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View();
                }
                var uniformesActualizar = Mapper.Map<DATA.Uniformes>(uniformes);
                uni.ActualizarUniformes(uniformesActualizar);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Producto/Delete/5
        public ActionResult Delete(int id)
        {
            uni.EliminarUniformes(id);
            return View();
        }
    }
}

SAMHS/SAMHS.UI/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

SAMHS/SAMHS.UI/Views/Home/Contact.cshtml
@{
	ViewBag.Title = "Informacion de Contacto";
}
<h2>Información de Contacto</h2>
@*<h3>@ViewBag.Message</h3>*@

<address>
	Escuela<br />
	Paso Ancho, de Educación Vial (INA) 50mts Sur y 25mts Oeste<br />
	<abbr title="Phone">P:</abbr>
	2286 4176
</address>

<address>
	<strong>Correo:</strong>   <a href="mailto:info@mounthopeschool.com">info@mounthopeschool.com</a><br />

</address>

<td>   Derechos reservados </td>
<td style="text-align:center;">
	Mapa de ubicacion <br>
	<a href="https://goo.gl/maps/pwq2WB2z92u" target="new">
		<img src="../Imagenes/mapa.PNG" alt="Mapa de ubicación" width="25%">
	</a>
</td>

<td style="text-align:center;">
	Redes Sociales <br>
	<a href="https://www.facebook.com/Mount-Hope-School-127391963942303/" target="new">
		<img src="../Imagenes/facebook55.png" alt="Imagen facebook">
	</a>
	<a href="https://twitter.com/?lang=es" target="new">
		<img src="../Imagenes/twitter13.png" alt="Imagen twitter">
</td>
             </a>
        </tr>

SAMHS/SAMHS.UI/Views/Home/Deposito.cshtml
@{
	ViewBag.Title = "Deposito";
}

<h2>Deposito</h2>
<h2 class="text-danger">@ViewBag.Error</h2>
<h2 class="text-success">@ViewBag.Correcto</h2>


<form class="jumbotron">
	<p>
		En esta página podrá subir el documeto o factura de un depósito realizado.
        Para reportar un nuevo depósito, sube el archivo. En caso de que tener alguna duda sobre el estado de su depósito, por favor comunicarse con  adeministración para mas información.
	</p>
</form>

<form class="jumbotron" method="post" enctype="multipart/form-data">
	<div class="col-lg-12">
		<input type="file" name="file" />
	</div>

	<div>
		<button type="submit">Subir</button>
	</div>
</form>

SAMHS/SAMHS.UI/Views/Home/Home.cshtml
@{
	ViewBag.Title = "Home";
}
<div class="jumbotron">
	<img src="../Imagenes/logo.jpg" alt="logo" width="20%">

	<h1>Mount Hope School</h1>
	<p class="lead">Es una institución de educación primaria fundada en 1994</p>


	<h2>Home</h2>

</div>
<div class="jumbotron" >

	<p><a class="btn btn-default" onclick="location.href='@Url.Action("Index","Calendario")'">Calendario &raquo;</a></p>
	<p><a class="btn btn-default" onclick="location.href='@Url.Action("Index","Citas")'">Citas &raquo;</a></p>
	<p><a class="btn btn-default" onclick="location.href='@Url.Action("Index","Uniformes")'">Uniformes &raquo;</a></p>
	<p><a class="btn btn-default" onclick="location.href='@Url.Action("Index","Materiales")'">Materiales &raquo;</a></p>
	<p><a class="btn btn-default" onclick="location.href='@Url.Action("Deposito","Home")'">Envio de depositos &raquo;</a></p>
</div>

SAMHS/SAMHS.UI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
	<img src="../Imagenes/Encabezado.jpg" alt="imagen de encabezado" width="100%">

	<h1>Mount Hope School</h1>
	<p class="lead">Es una institución de educación primaria fundada en 1994</p>

</div>

<div class="row">
    <div class="col-md-4">
        <h2>Valores</h2>
		<p>
			<p>-Disciplina</p>
			<p>-Amor</p> 
			<p>-Conocimiento</p>
		</p>
        
    </div>
    <div class="col-md-4">
        <h2>Misión</h2>
		<p>Promover el desarrollo integral del ser humano, ofreciendo a los niños un clima afectivo y saludable que favorezca su desarrollo físico, emocional, moral, intelectual y creativo, a su vez permitiendo el desenvolvimiento de su autonomía, participación y la integridad en el proceso de enseñanza aprendizaje. </p>
      
    </div>
	<div class="col-md-4">
		<h2>Alianzas</h2>
		<p>Con instituciones muy importantes como el IMAS y la escuela de idiomas PAI.</p>
		<p><a class="btn btn-default" href="https://es.linkedin.com/pulse/pai-escuela-de-idiomas-proyecto-bien-social-zully-cordero-solis">PAI &raquo;</a></p>
		<p><a class="btn btn-default" href="http://www.imas.go.cr/">IMAS &raquo;</a></p>
	</div>
</div>